### ISSUE TITLE
link changes from https to http

### ISSUE THREAD

**Issue by fgayanilo** [mmisw/orr#5] opened 2019-10-30 14:51 UTC
If you visit https://mmisw.org/ont/cf/parameter and search (for example), 'latitude', the links are in http but the hyperlinks are in https. This link 'https://mmisw.org/ont/cf/parameter/latitude' will throw an error (IRI not found) but not if you manually change it to http://mmisw.org/ont/cf/parameter/latitude

**Comment by carueda** [comment] 2019-10-30 16:07
Thanks for reporting this issue:

Yes, the hyperlink here:

![image](https://user-images.githubusercontent.com/556505/67875762-0edf7300-faf4-11e9-84c8-e6e4f7b0b0d8.png)

should be: 

`https://mmisw.org/ont?iri=http://mmisw.org/ont/cf/parameter/latitude`

instead of:

`https://mmisw.org/ont/cf/parameter/latitude`

Alternatively, the ORR could also detect that there's actually such IRI if only the scheme _https_ is replaced by _http_  -- in fact I remember adding logic for this kind of replacements, so perhaps this is actually a regression.

@graybeal @lewismc FYI

**Comment by graybeal** [comment] 2019-10-30 16:40
Thanks Carlos for the comments.

I'm thinking the original work was to make all IRI resolution requests that are http get rewritten (by Apache) to https, and have the system respond only to the https (so that all requests are securely handled. (In other words, both http and https IRIs would work and be responded to securely using https.)  At least, that was the approach I was envisioning, and I still think it is the best and simplest long-term approach.

But we may have gone down a different path, so I can't say the best thing to do in this moment. This is an important thing to take care of if we can, and maybe we can create a new task to do the above if that isn't in the current scheme.

**Comment by carueda** [comment] 2019-10-30 16:57
The ORR at mmisw.org has been fully functional with https.

(The http-to-https redirection is actually unrelated to the issue here, but something I suggested long ago though so far unimplemented perhaps because of lack of response or "official" approval AFAICR, or simply because everyone forgot about it.   Nonong, you are welcome to enable it at any time ;)

**Comment by fgayanilo** [comment] 2019-10-30 18:42
Do we need to update the DB contents itself when I get to 'force' redirect all calls to https?

**Comment by carueda** [comment] 2019-10-30 18:54
No. This is just about http-to-https redirection. Thanks!

**Comment by fgayanilo** [comment] 2019-10-30 19:26
Redirect to https is done

**Comment by carueda** [comment] 2019-10-30 19:36
Just tried http://mmisw.org/ont , but gets redirected to https://mmisw.orgont . Seems like a slash is missing in the translation when there's a path in the original request. Thanks.

**Comment by fgayanilo** [comment] 2019-10-30 19:39
Ooops! thanks for the catch, done!

**Comment by carueda** [comment] 2024-08-14 02:07
Just checked and all re this ticket worked OK, so we surely forgot to close this as fixed... so, closing now.

**Closed as completed by carueda** 2024-08-14 02:07 UTC
Labels: bug
